// Generated by CoffeeScript 1.3.3
var LoginView;

LoginView = (function() {

  function LoginView() {
    var logo;
    this.window = Ti.UI.createWindow({
      width: "100%",
      height: "100%"
    });
    logo = Ti.UI.createLabel({
      top: "30dip",
      left: "30dip",
      text: "POGO"
    });
    this.window.add(logo);
  }

  LoginView.prototype.show = function() {
    return this.window.open();
  };

  return LoginView;

})();

module.exports = new LoginView();
