// Generated by CoffeeScript 1.3.3
var LoginView;

LoginView = (function() {

  function LoginView() {
    var logo;
    this.window = Ti.UI.createWindow({
      width: "100%",
      height: "100%",
      backgroundColor: "#ffffff"
    });
    logo = Ti.UI.createLabel({
      top: "30dip",
      left: "30dip",
      text: "POGO"
    });
    this.email = Ti.UI.createTextField({
      top: "90dip",
      left: "60dip",
      hintText: "Email Address",
      width: "200dip",
      height: "40dip",
      borderWidth: "1dip",
      borderColor: "#000000"
    });
    this.password = Ti.UI.createTextField({
      top: "140dip",
      left: "60dip",
      passwordMask: true,
      hintText: "Password",
      width: "200dip",
      height: "40dip",
      borderWidth: "1dip",
      borderColor: "#000000"
    });
    this.submit = Ti.UI.createButton({
      top: "190dip",
      left: "50dip",
      width: "200dip",
      title: "Submit"
    });
    this.submit.addEventListener("click", function(event) {
      return Ti.API.info("Logging in");
    });
    this.window.add(logo);
    this.window.add(this.email);
    this.window.add(this.password);
    this.window.add(this.submit);
  }

  LoginView.prototype.show = function() {
    return this.window.open();
  };

  return LoginView;

})();

module.exports = new LoginView();
